[tool.poetry]
name = "rasp-dashboard"
version = "0.1.0"
description = ""
authors = ["Dany A. Darghouth <dany.al-moghrabi@etu.unige.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
